version: "3.7"

services:
  # web server
  nginx:
    image: nginx:latest
    volumes:
      - ./log/nginx:/var/log/nginx
      # app
      - ./app/src:/usr/share/nginx/html
      - ./app/www:/www/
      # nginx configs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      # certificates
      - ./nginx/ca/server.crt/:/etc/nginx/server.crt:ro
      - ./nginx/ca/server.key/:/etc/nginx/server.key:ro

  # php-fpm
  php-fpm:
    build: ./php-fpm
    volumes:
      - ./log/php-fpm:/var/log/php-fpm
      - ./app/www:/www/
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
    environment:
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_TABLE_PREFIX=${MYSQL_TABLE_PREFIX}
      - SITE_URL=${SITE_URL}
      - CACHE_PREFIX=${CACHE_PREFIX}
      - SITE_SESSIONNAME=${SITE_SESSIONNAME}
      - UUID=${UUID}

  # database
  mysql:
    image: mysql:5.7
    ports:
      # Allow client to access 3306
      - "3306:3306"
    volumes:
      # NOTE: your data will be stored in ./mysql
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-your_mysql_password}

  pma:
    image: phpmyadmin/phpmyadmin
    env_file: 
      - .env
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: ${PMA_UPLOAD_LIMIT:-100M}
    ports:
      - "8090:80"


  front:
    tty: true
    build:
      context: ./app/www/gorodskie-bani.ru
      # network: ${NETWORK_NAME:-prisma-cms-default}
      args: 
        - SITE=${SITE:-boilerplate}
        - ROLE=FRONT
        - ENV_MODE=development
        - endpoint=${dev_endpoint}
    # volumes:
      # - schema:/www/${SITE:-boilerplate}/src/schema
      # - shared:/www/${SITE:-boilerplate}/shared
      # - ./prisma-cms/${SITE:-boilerplate}/shared:/www/${SITE:-boilerplate}/shared
      # - ./prisma-cms/${SITE:-boilerplate}/uploads:/www/${SITE:-boilerplate}/uploads
    env_file: 
      - .env
    environment:
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_TABLE_PREFIX=${MYSQL_TABLE_PREFIX}
      - SITE_URL=${SITE_URL}
      - ENV_MODE=development
