version: "3.7"

services:
  nginx:
    restart: unless-stopped

  php-fpm:
    restart: unless-stopped
    # ports:
    #   - "80:80"
    #   - "443:443"

  mysql:
    restart: unless-stopped

  front_old:
    restart: unless-stopped
    build:
      args: 
        - ENV_MODE=production
    environment:
      - ENV_MODE=production
    command: yarn start:prod

  nextjs:
    restart: unless-stopped
    environment: 
      ENV_MODE: production
    build:
      args: 
        - ENV_MODE=production
        - endpoint=${prod_endpoint}
    command: bash -c "yarn start"
