version: "3.7"

services:
  nginx:
    ports:
      - "8082:80"
    volumes:
      - ./app/src:/usr/share/nginx/html

  php-fpm:
    ports:
      - "9000:9000"
    volumes:
      - ./log/php-fpm:/var/log/php-fpm
      - ./app/src:/usr/share/nginx/html

  mysql:
    ports:
      # Allow client to access 3306
      - "3306:3306"

  pma:
    ports:
      - "8090:80"

  front_old:
    volumes:
      - ./app/www/gorodskie-bani.ru/assets/components/modxsite/templates/v2.0/package.json:/www/${SITE:-boilerplate}/package.json
      - ./app/www/gorodskie-bani.ru/assets/components/modxsite/templates/v2.0/internals:/www/${SITE:-boilerplate}/internals
      - ./app/www/gorodskie-bani.ru/assets/components/modxsite/templates/v2.0/app:/www/${SITE:-boilerplate}/app
      - ./app/www/gorodskie-bani.ru/assets/components/modxsite/templates/v2.0/server:/www/${SITE:-boilerplate}/server
    # command: bash -c "yarn deploy && yarn start"
    command: yarn start
    ports:
      - 8400:3400

  nextjs:
    volumes:
      - ./prisma-cms/${SITE:-boilerplate}/src:/www/${SITE:-boilerplate}/src
      - ./prisma-cms/${SITE:-boilerplate}/server:/www/${SITE:-boilerplate}/server
      - ./prisma-cms/${SITE:-boilerplate}/prisma:/www/${SITE:-boilerplate}/prisma
    command: yarn dev
    ports:
      - 3000:3000
